// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIh5ReB50eJO4XsrYRfX7rSTikT3GiExc',
    appId: '1:939036758751:web:1a1d457787fe15c18e0f6a',
    messagingSenderId: '939036758751',
    projectId: 'yayasanbudidharmakirt',
    authDomain: 'yayasanbudidharmakirt.firebaseapp.com',
    databaseURL: 'https://yayasanbudidharmakirt-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yayasanbudidharmakirt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRdioeIRas1MMA4FfM7nNg0LOe0eLX98',
    appId: '1:939036758751:android:c88c2a311ecd30fc8e0f6a',
    messagingSenderId: '939036758751',
    projectId: 'yayasanbudidharmakirt',
    databaseURL: 'https://yayasanbudidharmakirt-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yayasanbudidharmakirt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPsBdh8q5Faa01T4lLRjNhl-wQl_6UpR4',
    appId: '1:939036758751:ios:0c299247c61d6bee8e0f6a',
    messagingSenderId: '939036758751',
    projectId: 'yayasanbudidharmakirt',
    databaseURL: 'https://yayasanbudidharmakirt-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yayasanbudidharmakirt.firebasestorage.app',
    iosBundleId: 'com.example.flutterNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPsBdh8q5Faa01T4lLRjNhl-wQl_6UpR4',
    appId: '1:939036758751:ios:453655bb15e3e6868e0f6a',
    messagingSenderId: '939036758751',
    projectId: 'yayasanbudidharmakirt',
    databaseURL: 'https://yayasanbudidharmakirt-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yayasanbudidharmakirt.firebasestorage.app',
    iosBundleId: 'com.example.flutterNew.RunnerTests',
  );
}
