// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCedhnir1U8IQyM4AIxAIAru2LTSTAFodU',
    appId: '1:707078594580:web:10b94785ae080cf54cc701',
    messagingSenderId: '707078594580',
    projectId: 'gabut-project-acc63',
    authDomain: 'gabut-project-acc63.firebaseapp.com',
    databaseURL: 'https://gabut-project-acc63-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gabut-project-acc63.firebasestorage.app',
    measurementId: 'G-YYM5HMD92Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_teeu77ChjEJvJkU_RsAUCkiWQvcVAZs',
    appId: '1:707078594580:android:de3b11653de07ffc4cc701',
    messagingSenderId: '707078594580',
    projectId: 'gabut-project-acc63',
    databaseURL: 'https://gabut-project-acc63-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gabut-project-acc63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnyl-jKIKj_tYNeMcNli_6ezGekzeKxF0',
    appId: '1:707078594580:ios:9385382912f483e04cc701',
    messagingSenderId: '707078594580',
    projectId: 'gabut-project-acc63',
    databaseURL: 'https://gabut-project-acc63-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gabut-project-acc63.firebasestorage.app',
    iosBundleId: 'com.example.flutterNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnyl-jKIKj_tYNeMcNli_6ezGekzeKxF0',
    appId: '1:707078594580:ios:81f577d36366a19f4cc701',
    messagingSenderId: '707078594580',
    projectId: 'gabut-project-acc63',
    databaseURL: 'https://gabut-project-acc63-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gabut-project-acc63.firebasestorage.app',
    iosBundleId: 'com.example.flutterNew.RunnerTests',
  );
}
